-- Execute este arquivo uma vez no SQL Editor do Supabase.
create table if not exists public.publications (
  id bigint generated by default as identity primary key,
  title text not null,
  authors text not null,
  venue text not null,
  year integer not null check (year between 1900 and 2100),
  type text not null default 'Artigo',
  doi text,
  abstract text,
  pdf_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.publications enable row level security;

drop policy if exists "Publications are publicly readable" on public.publications;
create policy "Publications are publicly readable" on public.publications
  for select using (true);

drop policy if exists "Owner can insert publications" on public.publications;
create policy "Owner can insert publications" on public.publications
  for insert to authenticated with check (
    lower(coalesce(auth.jwt() ->> 'email','')) in ('faculdadebc1@gmail.com','eng.beniciobarbosa@gmail.com')
  );

drop policy if exists "Owner can update publications" on public.publications;
create policy "Owner can update publications" on public.publications
  for update to authenticated using (
    lower(coalesce(auth.jwt() ->> 'email','')) in ('faculdadebc1@gmail.com','eng.beniciobarbosa@gmail.com')
  ) with check (
    lower(coalesce(auth.jwt() ->> 'email','')) in ('faculdadebc1@gmail.com','eng.beniciobarbosa@gmail.com')
  );

drop policy if exists "Owner can delete publications" on public.publications;
create policy "Owner can delete publications" on public.publications
  for delete to authenticated using (
    lower(coalesce(auth.jwt() ->> 'email','')) in ('faculdadebc1@gmail.com','eng.beniciobarbosa@gmail.com')
  );

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('publication-pdfs','publication-pdfs',true,26214400,array['application/pdf'])
on conflict (id) do update set public=true,file_size_limit=26214400,allowed_mime_types=array['application/pdf'];

drop policy if exists "PDFs are publicly readable" on storage.objects;
create policy "PDFs are publicly readable" on storage.objects
  for select using (bucket_id='publication-pdfs');

drop policy if exists "Owner can upload PDFs" on storage.objects;
create policy "Owner can upload PDFs" on storage.objects
  for insert to authenticated with check (
    bucket_id='publication-pdfs' and
    lower(coalesce(auth.jwt() ->> 'email','')) in ('faculdadebc1@gmail.com','eng.beniciobarbosa@gmail.com')
  );

drop policy if exists "Owner can update PDFs" on storage.objects;
create policy "Owner can update PDFs" on storage.objects
  for update to authenticated using (
    bucket_id='publication-pdfs' and
    lower(coalesce(auth.jwt() ->> 'email','')) in ('faculdadebc1@gmail.com','eng.beniciobarbosa@gmail.com')
  );

drop policy if exists "Owner can delete PDFs" on storage.objects;
create policy "Owner can delete PDFs" on storage.objects
  for delete to authenticated using (
    bucket_id='publication-pdfs' and
    lower(coalesce(auth.jwt() ->> 'email','')) in ('faculdadebc1@gmail.com','eng.beniciobarbosa@gmail.com')
  );

insert into public.publications (title,authors,venue,year,type)
select * from (values
 ('Optimal Trajectory Planning for Aerial Threat Neutralization Using a Multi-Drone System with Limited Resources','Benicio Barbosa Cruz, Jorge Antonio Ricardo Jr., Rubens Junqueira Magalhães Afonso, Davi Antônio dos Santos','COBEM 2025',2025,'Conference paper'),
 ('Sistema de Detecção de Gestos Para Controle de Drones','João Pedro Santana Silva Santos, Benicio Barbosa Cruz, Stephanie K. A. Sousa, et al.','Artigo publicado',2025,'Artigo'),
 ('Planejamento Ótimo de Trajetórias para Neutralização de Ameaças Aéreas com Sistema Multidrones e Recursos Limitados','Benicio Barbosa Cruz','Instituto Tecnológico de Aeronáutica',2025,'Dissertação de mestrado'),
 ('Low-Cost Optical Communication System for Short-Range Underwater Applications','Benicio Barbosa Cruz, Stephanie K. Alves de Sousa, Phillipe C. Santos, Fábio L. Sá Prudente','Conference paper',2025,'Conference paper'),
 ('A Mixed-Reality Experimental Indoor Testbed for Evaluation of Drone Flight Control Methods','Benicio Barbosa Cruz, Jorge Antonio Ricardo Jr., Davi Antônio dos Santos','CBA 2024',2024,'Conference paper'),
 ('Desenvolvimento de um Veículo Subaquático Remotamente Operado, de Baixo Custo, para Fins Educacionais','Leonardo A. N. Fontes, Benicio Barbosa Cruz, Stephanie K. Alves, et al.','Conference paper',2024,'Artigo em congresso')
) as seed(title,authors,venue,year,type)
where not exists (select 1 from public.publications);
