const client=window.supabase.createClient("https://vfyiczqntletivvxvpmo.supabase.co","sb_publishable_radG_i41rNtT3pI_YhXUpg_qbvl5nJO");
const allowed=["faculdadebc1@gmail.com","eng.beniciobarbosa@gmail.com"],$=id=>document.getElementById(id);let publications=[],editing=null;
async function checkSession(){const {data:{session}}=await client.auth.getSession();const email=session?.user?.email?.toLowerCase();const ok=email&&allowed.includes(email);$("loginPanel").hidden=!!ok;$("manager").hidden=!ok;$("signOut").hidden=!ok;if(ok)load();}
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginStatus").textContent="Entrando…";const {error}=await client.auth.signInWithPassword({email:$("loginEmail").value,password:$("loginPassword").value});$("loginStatus").textContent=error?"Não foi possível entrar. Verifique o e-mail e a senha.":"";if(!error)checkSession();};
$("signOut").onclick=async()=>{await client.auth.signOut();location.reload();};
async function load(){const {data,error}=await client.from("publications").select("*").order("year",{ascending:false}).order("created_at",{ascending:false});if(error){$("items").innerHTML=`<p>Erro ao carregar: ${error.message}</p>`;return}publications=data||[];$("count").textContent=`${publications.length} ${publications.length===1?"registro":"registros"}`;$("items").innerHTML=publications.map(p=>`<article class="${editing?.id===p.id?"selected":""}"><time>${p.year}</time><div><small>${escapeHtml(p.type)}</small><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.venue)}</p>${p.pdf_path?'<span class="pdf-badge">PDF anexado</span>':''}</div><div class="manager-actions"><button data-edit="${p.id}">Editar</button><button class="danger" data-delete="${p.id}">Excluir</button></div></article>`).join("");document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>edit(Number(b.dataset.edit)));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>remove(Number(b.dataset.delete)));}
function escapeHtml(s=""){return String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function edit(id){editing=publications.find(p=>p.id===id);const f=$("publicationForm");["title","authors","venue","year","type","doi","abstract"].forEach(k=>f.elements[k].value=editing[k]||"");$("formTitle").textContent="Editar publicação";$("submitButton").textContent="Salvar alterações";$("cancelEdit").hidden=false;$("removePdfLabel").hidden=!editing.pdf_path;$("formStatus").textContent="";load();f.scrollIntoView({behavior:"smooth"});}
function reset(){editing=null;$("publicationForm").reset();$("formTitle").textContent="Nova publicação";$("submitButton").textContent="Cadastrar publicação";$("cancelEdit").hidden=true;$("removePdfLabel").hidden=true;$("formStatus").textContent="";load();}$("cancelEdit").onclick=reset;
$("publicationForm").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,file=f.elements.pdf.files[0];if(file&&(file.type!=="application/pdf"||file.size>25*1024*1024)){$("formStatus").textContent="Selecione um PDF de até 25 MB.";return}$("formStatus").textContent="Salvando…";let pdfPath=editing?.pdf_path||null;if((f.elements.removePdf.checked&&pdfPath)||file){if(pdfPath)await client.storage.from("publication-pdfs").remove([pdfPath]);pdfPath=null}if(file){pdfPath=`${Date.now()}-${crypto.randomUUID()}.pdf`;const {error}=await client.storage.from("publication-pdfs").upload(pdfPath,file,{contentType:"application/pdf"});if(error){$("formStatus").textContent=`Erro no PDF: ${error.message}`;return}}const payload={title:f.elements.title.value.trim(),authors:f.elements.authors.value.trim(),venue:f.elements.venue.value.trim(),year:Number(f.elements.year.value),type:f.elements.type.value,doi:f.elements.doi.value.trim()||null,abstract:f.elements.abstract.value.trim()||null,pdf_path:pdfPath,updated_at:new Date().toISOString()};const result=editing?await client.from("publications").update(payload).eq("id",editing.id):await client.from("publications").insert(payload);if(result.error){$("formStatus").textContent=`Erro: ${result.error.message}`;return}$("formStatus").textContent="Publicação salva.";setTimeout(reset,700);};
async function remove(id){const p=publications.find(x=>x.id===id);if(!confirm(`Excluir definitivamente “${p.title}”?`))return;if(p.pdf_path)await client.storage.from("publication-pdfs").remove([p.pdf_path]);const {error}=await client.from("publications").delete().eq("id",id);if(error)alert(`Erro: ${error.message}`);else{if(editing?.id===id)reset();else load();}}
client.auth.onAuthStateChange(()=>checkSession());checkSession();
